steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/mlops-1-494812/ml-models/bank-campaign-model:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/mlops-1-494812/ml-models/bank-campaign-model:latest']

- name: 'us-central1-docker.pkg.dev/mlops-1-494812/ml-models/bank-campaign-model:latest'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'bank_campaign_model_training.py', 'gs://us-central1-mlops-airflow-0d99ad20-bucket/dags']

images:
- 'us-central1-docker.pkg.dev/mlops-1-494812/ml-models/bank-campaign-model:latest'

options:
  logging: CLOUD_LOGGING_ONLY
