steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ml-models/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-models/bank-campaign-model']

- name: 'gcr.io/ml-models/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Durga592/ml-model-training.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'ml-model-training/bank_campaign_model_training.py', 'gs://us-central1-mlops-airflow-0d99ad20-bucket/dags']

images:
- 'gcr.io/ml-models/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY
